name: auto_go_route_generator
version: 1.1.0
description: Code generator for auto_go_route package

homepage: https://github.com/itsarvinddev/auto_go_route
repository: https://github.com/itsarvinddev/auto_go_route
issue_tracker: https://github.com/itsarvinddev/auto_go_route/issues
documentation: https://github.com/itsarvinddev/auto_go_route/wiki

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  code_builder: ^4.11.0
  dart_style: ^3.1.2
  source_gen: ">=3.0.0 <5.0.0"
  glob: ^2.1.3

dev_dependencies:
  build_runner: ">=2.0.0 <5.0.0"
