import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'src/generators/route_generator.dart';

/// Builder for auto_go_route code generation with enhanced error handling
Builder autoGoRouteBuilder(BuilderOptions options) {
  return PartBuilder(
    [AutoGoRouteGenerator()],
    '.routes.g.dart',
    options: options,
    header: '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by auto_go_route_generator

// ignore_for_file: type=lint
// ignore_for_file: unused_element
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_literals_to_create_immutables
''',
  );
}
