import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'src/generators/route_generator.dart';

/// The `auto_go_route_generator:auto_go_route_builder` factory.
///
/// Supported options:
///
/// ```yaml
/// targets:
///   $default:
///     builders:
///       auto_go_route_generator:auto_go_route_builder:
///         options:
///           source_globs:
///             - lib/**/*.dart
///             - lib/src/features/**/*.dart
/// ```
///
/// `source_globs` narrows (or widens) the assets scanned for `@AutoGoRoute`
/// annotations. Narrowing it to the directories that actually hold routes is
/// the cheapest way to speed up a very large package.
Builder autoGoRouteBuilder(BuilderOptions options) {
  final configured = options.config['source_globs'];
  final sourceGlobs = switch (configured) {
    final List<dynamic> list => list.map((e) => e.toString()).toList(),
    final String single => [single],
    _ => null,
  };

  return PartBuilder(
    [AutoGoRouteGenerator(sourceGlobs: sourceGlobs)],
    '.routes.g.dart',
    options: options,
    header: '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by auto_go_route_generator.

// ignore_for_file: type=lint
// ignore_for_file: unnecessary_string_escapes
''',
  );
}
