name: auto_go_route
version: 1.1.0
description: A powerful, type-safe, and feature-rich routing package for Flutter GoRouter with automatic code generation.

homepage: https://github.com/itsarvinddev/auto_go_route
repository: https://github.com/itsarvinddev/auto_go_route
issue_tracker: https://github.com/itsarvinddev/auto_go_route/issues
documentation: https://pub.dev/documentation/ai_barcode_scanner/latest/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ">=2.0.0 <5.0.0"
  auto_go_route_generator:
    path: generator/

topics:
  - routing
  - navigation
  - auto-route
  - go-router
  - type-safety

screenshots:
  - description: "Poster of auto_go_route"
    path: "auto_go_route.webp"

funding:
  - https://github.com/sponsors/itsarvinddev

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
