// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by auto_go_route_generator

// ignore_for_file: type=lint
// ignore_for_file: unused_element
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_literals_to_create_immutables

part of 'app_router.dart';

// **************************************************************************
// AutoGoRouteGenerator
// **************************************************************************

// ignore_for_file: unused_element

typedef _RouteRefSettingsRoute = SettingsRoute;
typedef _RouteRefProfileRoute = ProfileRoute;
typedef _RouteRefLegacyProfileRoute = LegacyProfileRoute;
typedef _RouteRefLoginRoute = LoginRoute;
typedef _RouteRefNewFeatureRoute = NewFeatureRoute;
typedef _RouteRefProductListRoute = ProductListRoute;
typedef _RouteRefProductDetailsRoute = ProductDetailsRoute;
typedef _RouteRefProductReviewsRoute = ProductReviewsRoute;
typedef _RouteRefProductOffersRoute = ProductOffersRoute;
typedef _RouteRefHomeRoute = HomeRoute;
typedef _RouteRefDashboardShell = DashboardShell;

abstract class _$AppRouter {
  List<RoutePaths> get allRoutes {
    return [
      settingsRouteRoute,
      profileRouteRoute,
      legacyProfileRouteRoute,
      loginRouteRoute,
      newFeatureRouteRoute,
      productListRouteRoute,
      productDetailsRouteRoute,
      productReviewsRouteRoute,
      productOffersRouteRoute,
      homeRouteRoute,
    ];
  }

  List<ShellRoutePaths> get allShells {
    return [dashboardShellRoute];
  }

  List<RouteBase> _buildNestedRoutes() {
    return [
      legacyProfileRouteRoute.toGoRoute(routes: []),
      loginRouteRoute.toGoRoute(routes: []),
      newFeatureRouteRoute.toGoRoute(routes: []),
      productListRouteRoute.toGoRoute(routes: []),
      productDetailsRouteRoute.toGoRoute(
        routes: [
          productReviewsRouteRoute.toGoRoute(routes: []),
          productOffersRouteRoute.toGoRoute(routes: []),
        ],
      ),
      GoRoute(
        path: '/',
        redirect: (context, state) {
          if (state.fullPath == '/') {
            return '/home';
          }
          return null;
        },
        routes: [
          StatefulShellRoute.indexedStack(
            builder: dashboardShellRoute.builder,
            branches: [
              StatefulShellBranch(
                routes: [homeRouteRoute.toGoRoute(routes: [])],
              ),
              StatefulShellBranch(
                routes: [profileRouteRoute.toGoRoute(routes: [])],
              ),
              StatefulShellBranch(
                routes: [settingsRouteRoute.toGoRoute(routes: [])],
              ),
            ],
          ),
        ],
      ),
    ];
  }

  GoRouter buildRouter([GlobalKey<NavigatorState>? navigatorKey]) {
    return GoRouter(
      redirect: loggingMiddleware,
      errorBuilder: (context, state) => ErrorScreen.new(error: state.error),
      navigatorKey: navigatorKey,
      routes: _buildNestedRoutes(),
    );
  }

  SettingsRouteRoute get settingsRouteRoute {
    return SettingsRouteRoute();
  }

  ProfileRouteRoute get profileRouteRoute {
    return ProfileRouteRoute();
  }

  LegacyProfileRouteRoute get legacyProfileRouteRoute {
    return LegacyProfileRouteRoute();
  }

  LoginRouteRoute get loginRouteRoute {
    return LoginRouteRoute();
  }

  NewFeatureRouteRoute get newFeatureRouteRoute {
    return NewFeatureRouteRoute();
  }

  ProductListRouteRoute get productListRouteRoute {
    return ProductListRouteRoute();
  }

  ProductDetailsRouteRoute get productDetailsRouteRoute {
    return ProductDetailsRouteRoute();
  }

  ProductReviewsRouteRoute get productReviewsRouteRoute {
    return ProductReviewsRouteRoute();
  }

  ProductOffersRouteRoute get productOffersRouteRoute {
    return ProductOffersRouteRoute();
  }

  HomeRouteRoute get homeRouteRoute {
    return HomeRouteRoute();
  }

  DashboardShellRoute get dashboardShellRoute {
    return DashboardShellRoute();
  }
}

class SettingsRouteRoute extends NestedRoutePaths {
  SettingsRouteRoute()
    : super(
        parentPath: '/',
        path: '/settings',
        name: 'settingsRoute',
        builder: (context, state) => SettingsRoute(),
      );
}

class ProfileRouteRoute extends NestedRoutePaths {
  ProfileRouteRoute()
    : super(
        parentPath: '/',
        path: '/profile',
        name: 'profileRoute',
        builder: (context, state) => ProfileRoute(),
      );
}

class LegacyProfileRouteRoute extends RoutePaths {
  LegacyProfileRouteRoute()
    : super(
        path: '/account',
        name: 'legacyProfileRoute',
        middleware: const [legacyProfileRedirect],
        builder: (context, state) => LegacyProfileRoute(),
      );
}

class LoginRouteRoute extends RoutePaths {
  LoginRouteRoute()
    : super(
        path: '/login',
        name: 'loginRoute',
        builder: (context, state) => LoginRoute(),
      );
}

class NewFeatureRouteRoute extends RoutePaths {
  NewFeatureRouteRoute()
    : super(
        path: '/new-feature',
        name: 'newFeatureRoute',
        middleware: const [featureFlagMiddleware],
        builder: (context, state) => NewFeatureRoute(),
      );
}

class ProductListRouteRoute extends RoutePaths {
  ProductListRouteRoute()
    : super(
        path: '/products',
        name: 'productListRoute',
        builder: (context, state) => ProductListRoute(),
      );
}

class ProductDetailsRouteRoute extends RoutePaths {
  ProductDetailsRouteRoute()
    : super(
        path: '/products/:id',
        name: 'productDetailsRoute',
        builder: (context, state) =>
            ProductDetailsRoute(id: state.getParam<String>('id')),
      );
}

class ProductReviewsRouteRoute extends NestedRoutePaths {
  ProductReviewsRouteRoute()
    : super(
        parentPath: '/products/:id',
        path: 'reviews',
        name: 'productReviewsRoute',
        builder: (context, state) =>
            ProductReviewsRoute(id: state.getParam<String>('id')),
      );
}

class ProductOffersRouteRoute extends NestedRoutePaths {
  ProductOffersRouteRoute()
    : super(
        parentPath: '/products/:id',
        path: 'offers',
        name: 'productOffersRoute',
        builder: (context, state) =>
            ProductOffersRoute(id: state.getParam<String>('id')),
      );
}

class HomeRouteRoute extends NestedRoutePaths {
  HomeRouteRoute()
    : super(
        parentPath: '/',
        path: '/home',
        name: 'homeRoute',
        builder: (context, state) => HomeRoute(
          featureDisabled: state.getParam<String>('featureDisabled'),
        ),
      );
}

class DashboardShellRoute extends ShellRoutePaths {
  DashboardShellRoute()
    : super(
        path: '/',

        isStateful: true,
        builder: (context, state, child) =>
            DashboardShell(navigationShell: child as StatefulNavigationShell),
      );
}
