// dart format width=80
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by auto_go_route_generator

// ignore_for_file: type=lint
// ignore_for_file: unused_element
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_literals_to_create_immutables

part of 'app_router.dart';

// **************************************************************************
// AutoGoRouteGenerator
// **************************************************************************

// ignore_for_file: unused_element

typedef _RouteRefSettingsRoute = SettingsRoute;
typedef _RouteRefLegacyProfileRoute = LegacyProfileRoute;
typedef _RouteRefProfileTab = ProfileTab;
typedef _RouteRefSettingsTab = SettingsTab;
typedef _RouteRefNotificationsTab = NotificationsTab;
typedef _RouteRefNotificationDetail = NotificationDetail;
typedef _RouteRefNotificationAction = NotificationAction;
typedef _RouteRefLoginRoute = LoginRoute;
typedef _RouteRefNewFeatureRoute = NewFeatureRoute;
typedef _RouteRefBottomSheetContent = BottomSheetContent;
typedef _RouteRefBottomSheetNextRoute = BottomSheetNextRoute;
typedef _RouteRefProductListRoute = ProductListRoute;
typedef _RouteRefProductDetailsRoute = ProductDetailsRoute;
typedef _RouteRefProductReviewsRoute = ProductReviewsRoute;
typedef _RouteRefProductOffersRoute = ProductOffersRoute;
typedef _RouteRefHomeRoute = HomeRoute;
typedef _RouteRefDashboardShell = DashboardShell;
typedef _RouteRefProfileRoute = ProfileRoute;
typedef _RouteRefBottomSheetRoute = BottomSheetRoute;

abstract class _$AppRouter {
  List<RoutePaths> get allRoutes {
    return [
      settingsRouteRoute,
      legacyProfileRouteRoute,
      profileTabRoute,
      settingsTabRoute,
      notificationsTabRoute,
      notificationDetailRoute,
      notificationActionRoute,
      loginRouteRoute,
      newFeatureRouteRoute,
      bottomSheetContentRoute,
      bottomSheetNextRouteRoute,
      productListRouteRoute,
      productDetailsRouteRoute,
      productReviewsRouteRoute,
      productOffersRouteRoute,
      homeRouteRoute,
    ];
  }

  List<ShellRoutePaths> get allShells {
    return [dashboardShellRoute, profileRouteRoute, bottomSheetRouteRoute];
  }

  List<RouteBase> _buildNestedRoutes() {
    return [
      legacyProfileRouteRoute.toGoRoute(routes: []),
      loginRouteRoute.toGoRoute(routes: []),
      newFeatureRouteRoute.toGoRoute(routes: []),
      productListRouteRoute.toGoRoute(routes: []),
      productDetailsRouteRoute.toGoRoute(
        routes: [
          productReviewsRouteRoute.toGoRoute(routes: []),
          productOffersRouteRoute.toGoRoute(routes: []),
        ],
      ),
      ShellRoute(
        pageBuilder: adaptiveOverlayPageBuilder,
        routes: [
          bottomSheetContentRoute.toGoRoute(routes: []),
          bottomSheetNextRouteRoute.toGoRoute(routes: []),
        ],
      ),
      GoRoute(
        path: '/',
        redirect: (context, state) {
          if (state.uri.path == '/') {
            return '/home-screen';
          }
          return null;
        },
        routes: [
          StatefulShellRoute.indexedStack(
            builder: dashboardShellRoute.builder,
            branches: [
              StatefulShellBranch(
                routes: [homeRouteRoute.toGoRoute(routes: [])],
              ),
              StatefulShellBranch(
                routes: [
                  profileRouteRoute.toShellRoute(
                    routes: [
                      profileTabRoute.toGoRoute(routes: []),
                      settingsTabRoute.toGoRoute(routes: []),
                      notificationsTabRoute.toGoRoute(
                        routes: [
                          notificationDetailRoute.toGoRoute(
                            routes: [
                              notificationActionRoute.toGoRoute(routes: []),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              StatefulShellBranch(
                routes: [settingsRouteRoute.toGoRoute(routes: [])],
              ),
            ],
          ),
        ],
      ),
    ];
  }

  GoRouter buildRouter([GlobalKey<NavigatorState>? navigatorKey]) {
    return GoRouter(
      redirect: loggingMiddleware,
      errorBuilder: (context, state) => ErrorScreen.new(error: state.error),
      navigatorKey: navigatorKey,
      routes: _buildNestedRoutes(),
    );
  }

  SettingsRouteRoute get settingsRouteRoute {
    return SettingsRouteRoute();
  }

  LegacyProfileRouteRoute get legacyProfileRouteRoute {
    return LegacyProfileRouteRoute();
  }

  ProfileTabRoute get profileTabRoute {
    return ProfileTabRoute();
  }

  SettingsTabRoute get settingsTabRoute {
    return SettingsTabRoute();
  }

  NotificationsTabRoute get notificationsTabRoute {
    return NotificationsTabRoute();
  }

  NotificationDetailRoute get notificationDetailRoute {
    return NotificationDetailRoute();
  }

  NotificationActionRoute get notificationActionRoute {
    return NotificationActionRoute();
  }

  LoginRouteRoute get loginRouteRoute {
    return LoginRouteRoute();
  }

  NewFeatureRouteRoute get newFeatureRouteRoute {
    return NewFeatureRouteRoute();
  }

  BottomSheetContentRoute get bottomSheetContentRoute {
    return BottomSheetContentRoute();
  }

  BottomSheetNextRouteRoute get bottomSheetNextRouteRoute {
    return BottomSheetNextRouteRoute();
  }

  ProductListRouteRoute get productListRouteRoute {
    return ProductListRouteRoute();
  }

  ProductDetailsRouteRoute get productDetailsRouteRoute {
    return ProductDetailsRouteRoute();
  }

  ProductReviewsRouteRoute get productReviewsRouteRoute {
    return ProductReviewsRouteRoute();
  }

  ProductOffersRouteRoute get productOffersRouteRoute {
    return ProductOffersRouteRoute();
  }

  HomeRouteRoute get homeRouteRoute {
    return HomeRouteRoute();
  }

  DashboardShellRoute get dashboardShellRoute {
    return DashboardShellRoute();
  }

  ProfileRouteRoute get profileRouteRoute {
    return ProfileRouteRoute();
  }

  BottomSheetRouteRoute get bottomSheetRouteRoute {
    return BottomSheetRouteRoute();
  }
}

class SettingsRouteRoute extends NestedRoutePaths {
  SettingsRouteRoute()
    : super(
        parentPath: '',
        path: '/settings',
        name: 'settingsRoute',
        builder: (context, state) => SettingsRoute(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class LegacyProfileRouteRoute extends RoutePaths {
  LegacyProfileRouteRoute()
    : super(
        path: '/account',
        name: 'legacyProfileRoute',
        middleware: const [legacyProfileRedirect],
        builder: (context, state) => LegacyProfileRoute(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class ProfileTabRoute extends NestedRoutePaths {
  ProfileTabRoute()
    : super(
        parentPath: '',
        path: '/profile',
        name: 'profileTab',
        builder: (context, state) => ProfileTab(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class SettingsTabRoute extends NestedRoutePaths {
  SettingsTabRoute()
    : super(
        parentPath: '',
        path: '/settings-tab',
        name: 'settingsTab',
        builder: (context, state) => SettingsTab(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class NotificationsTabRoute extends NestedRoutePaths {
  NotificationsTabRoute()
    : super(
        parentPath: '',
        path: '/notifications',
        name: 'notificationsTab',
        builder: (context, state) => NotificationsTab(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class NotificationDetailRoute extends NestedRoutePaths {
  NotificationDetailRoute()
    : super(
        parentPath: '/notifications',
        path: '/:id',
        name: 'notificationDetail',
        builder: (context, state) => NotificationDetail(
          id: state.getParam<String>('id'),
          user: state.extra as User?,
        ),
      );

  String pathWith({required String id, Map<String, String>? queries}) {
    return pathWithParams({'id': id}, queries: queries);
  }
}

class NotificationActionRoute extends NestedRoutePaths {
  NotificationActionRoute()
    : super(
        parentPath: '/notifications/:id',
        path: '/action',
        name: 'notificationAction',
        builder: (context, state) =>
            NotificationAction(action: state.getParam<String>('action')),
      );

  String pathWith({required String id, Map<String, String>? queries}) {
    return pathWithParams({'id': id}, queries: queries);
  }
}

class LoginRouteRoute extends RoutePaths {
  LoginRouteRoute()
    : super(
        path: '/login',
        name: 'loginRoute',
        builder: (context, state) => LoginRoute(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class NewFeatureRouteRoute extends RoutePaths {
  NewFeatureRouteRoute()
    : super(
        path: '/new-feature',
        name: 'newFeatureRoute',
        middleware: const [featureFlagMiddleware],
        builder: (context, state) => NewFeatureRoute(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class BottomSheetContentRoute extends NestedRoutePaths {
  BottomSheetContentRoute()
    : super(
        parentPath: '',
        path: '/content',
        name: 'bottomSheetContent',
        builder: (context, state) => BottomSheetContent(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class BottomSheetNextRouteRoute extends NestedRoutePaths {
  BottomSheetNextRouteRoute()
    : super(
        parentPath: '',
        path: '/next',
        name: 'bottomSheetNext',
        builder: (context, state) => BottomSheetNextRoute(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class ProductListRouteRoute extends RoutePaths {
  ProductListRouteRoute()
    : super(
        path: '/products',
        name: 'productListRoute',
        builder: (context, state) => ProductListRoute(),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class ProductDetailsRouteRoute extends RoutePaths {
  ProductDetailsRouteRoute()
    : super(
        path: '/products/:id',
        name: 'productDetailsRoute',
        builder: (context, state) => ProductDetailsRoute(
          id: state.getParam<String>('id'),
          name: state.getParam<String>('name'),
          product: state.extra as Product?,
        ),
      );

  String pathWith({required String id, Map<String, String>? queries}) {
    return pathWithParams({'id': id}, queries: queries);
  }
}

class ProductReviewsRouteRoute extends NestedRoutePaths {
  ProductReviewsRouteRoute()
    : super(
        parentPath: '/products/:id',
        path: 'reviews',
        name: 'productReviewsRoute',
        builder: (context, state) =>
            ProductReviewsRoute(id: state.getParam<String>('id')),
      );

  String pathWith({required String id, Map<String, String>? queries}) {
    return pathWithParams({'id': id}, queries: queries);
  }
}

class ProductOffersRouteRoute extends NestedRoutePaths {
  ProductOffersRouteRoute()
    : super(
        parentPath: '/products/:id',
        path: 'offers',
        name: 'productOffersRoute',
        builder: (context, state) =>
            ProductOffersRoute(id: state.getParam<String>('id')),
      );

  String pathWith({required String id, Map<String, String>? queries}) {
    return pathWithParams({'id': id}, queries: queries);
  }
}

class HomeRouteRoute extends NestedRoutePaths {
  HomeRouteRoute()
    : super(
        parentPath: '',
        path: '/home-screen',
        name: 'homeRoute',
        builder: (context, state) => HomeRoute(
          featureDisabled: state.getParam<String>('featureDisabled'),
        ),
      );

  String pathWith({Map<String, String>? queries}) {
    return pathWithParams({}, queries: queries);
  }
}

class DashboardShellRoute extends ShellRoutePaths {
  DashboardShellRoute()
    : super(
        path: '/',

        isStateful: true,
        builder: (context, state, child) =>
            DashboardShell(navigationShell: child as StatefulNavigationShell),
      );
}

class ProfileRouteRoute extends ShellRoutePaths {
  ProfileRouteRoute()
    : super(
        path: '/profile-shell',

        isStateful: false,
        builder: (context, state, child) => ProfileRoute(child: child),
      );
}

class BottomSheetRouteRoute extends ShellRoutePaths {
  BottomSheetRouteRoute()
    : super(
        path: '/bottom-sheet',
        name: 'bottomSheetRoute',

        isStateful: false,
        builder: (context, state, child) => BottomSheetRoute(child: child),
      );
}

extension AutoGoRouteNavigation on BuildContext {
  void goToSettingsRoute({Map<String, String>? queries, Object? extra}) {
    go(SettingsRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToSettingsRoute<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      SettingsRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithSettingsRoute({Map<String, String>? queries, Object? extra}) {
    pushReplacement(
      SettingsRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToLegacyProfileRoute({Map<String, String>? queries, Object? extra}) {
    go(LegacyProfileRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToLegacyProfileRoute<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      LegacyProfileRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithLegacyProfileRoute({
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      LegacyProfileRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToProfileTab({Map<String, String>? queries, Object? extra}) {
    go(ProfileTabRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToProfileTab<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(ProfileTabRoute().pathWith(queries: queries), extra: extra);
  }

  void replaceWithProfileTab({Map<String, String>? queries, Object? extra}) {
    pushReplacement(ProfileTabRoute().pathWith(queries: queries), extra: extra);
  }

  void goToSettingsTab({Map<String, String>? queries, Object? extra}) {
    go(SettingsTabRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToSettingsTab<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(SettingsTabRoute().pathWith(queries: queries), extra: extra);
  }

  void replaceWithSettingsTab({Map<String, String>? queries, Object? extra}) {
    pushReplacement(
      SettingsTabRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToNotificationsTab({Map<String, String>? queries, Object? extra}) {
    go(NotificationsTabRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToNotificationsTab<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      NotificationsTabRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithNotificationsTab({
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      NotificationsTabRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToNotificationDetail({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    go(
      NotificationDetailRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  Future<T?> pushToNotificationDetail<T extends Object?>({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      NotificationDetailRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void replaceWithNotificationDetail({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      NotificationDetailRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void goToNotificationAction({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    go(
      NotificationActionRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  Future<T?> pushToNotificationAction<T extends Object?>({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      NotificationActionRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void replaceWithNotificationAction({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      NotificationActionRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void goToLoginRoute({Map<String, String>? queries, Object? extra}) {
    go(LoginRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToLoginRoute<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(LoginRouteRoute().pathWith(queries: queries), extra: extra);
  }

  void replaceWithLoginRoute({Map<String, String>? queries, Object? extra}) {
    pushReplacement(LoginRouteRoute().pathWith(queries: queries), extra: extra);
  }

  void goToNewFeatureRoute({Map<String, String>? queries, Object? extra}) {
    go(NewFeatureRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToNewFeatureRoute<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      NewFeatureRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithNewFeatureRoute({
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      NewFeatureRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToBottomSheetContent({Map<String, String>? queries, Object? extra}) {
    go(BottomSheetContentRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToBottomSheetContent<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      BottomSheetContentRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithBottomSheetContent({
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      BottomSheetContentRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToBottomSheetNext({Map<String, String>? queries, Object? extra}) {
    go(BottomSheetNextRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToBottomSheetNext<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      BottomSheetNextRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithBottomSheetNext({
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      BottomSheetNextRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToProductListRoute({Map<String, String>? queries, Object? extra}) {
    go(ProductListRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToProductListRoute<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      ProductListRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void replaceWithProductListRoute({
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      ProductListRouteRoute().pathWith(queries: queries),
      extra: extra,
    );
  }

  void goToProductDetailsRoute({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    go(
      ProductDetailsRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  Future<T?> pushToProductDetailsRoute<T extends Object?>({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      ProductDetailsRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void replaceWithProductDetailsRoute({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      ProductDetailsRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void goToProductReviewsRoute({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    go(
      ProductReviewsRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  Future<T?> pushToProductReviewsRoute<T extends Object?>({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      ProductReviewsRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void replaceWithProductReviewsRoute({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      ProductReviewsRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void goToProductOffersRoute({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    go(
      ProductOffersRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  Future<T?> pushToProductOffersRoute<T extends Object?>({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(
      ProductOffersRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void replaceWithProductOffersRoute({
    required String id,
    Map<String, String>? queries,
    Object? extra,
  }) {
    pushReplacement(
      ProductOffersRouteRoute().pathWith(id: id, queries: queries),
      extra: extra,
    );
  }

  void goToHomeRoute({Map<String, String>? queries, Object? extra}) {
    go(HomeRouteRoute().pathWith(queries: queries), extra: extra);
  }

  Future<T?> pushToHomeRoute<T extends Object?>({
    Map<String, String>? queries,
    Object? extra,
  }) {
    return push<T>(HomeRouteRoute().pathWith(queries: queries), extra: extra);
  }

  void replaceWithHomeRoute({Map<String, String>? queries, Object? extra}) {
    pushReplacement(HomeRouteRoute().pathWith(queries: queries), extra: extra);
  }
}
